require 'pathname'

module Twine
  module Formatters
    class AppleObjCTagHeader < Abstract
      include Twine::Placeholders

      attr_accessor :stringFileName

      def format_name
        'apple-objc-tag-header'
      end
      
      def extension
        '.h'
      end

      def self.can_handle_directory?(path)
        true
      end

      def default_file_name
        return 'R2Tag+TxtFileName.h'
      end

      def determine_language_given_path(path)
        raise 'not going to implement'
      end

      def format_file(lang)
        filePath = Pathname.new(@options[:output_path])
        self.stringFileName = filePath.basename.to_s[0..-4]
        impl = "R2Tag+" + self.stringFileName + ".h"
        @options[:output_path] = filePath.dirname + impl
        result = super + "\n\n@end\n"
      end

      def format_header(lang)
        %(/**
 * Header File
 * Generated by Twine #{Twine::VERSION}
 */

#import "R2Tag.h"

@interface R2Tag \(#{stringFileName}\)
)
      end

      def format_section_header(section)
        "#pragma mark - #{section.name}"
      end

      def key_value_pattern
        %(\n@property (nonatomic, readonly) NSString *%{key};)
      end

      def format_comment(definition, lang)
        comment = ''
        if definition.comment
          comment = "\n #{definition.comment}"
        end
        %(\n/**\n Translation in #{lang} :\n #{definition.translations[lang]}#{comment}\n*/)
      end

    end
  end
end

Twine::Formatters.formatters << Twine::Formatters::AppleObjCTagHeader.new
