require 'pathname'

module Twine
  module Formatters
    class AppleObjCImpl < Abstract
      include Twine::Placeholders

      attr_accessor :stringFileName

      def format_name
        'apple-objc-impl'
      end
      
      def extension
        '.hm'
      end

      def self.can_handle_directory?(path)
        true
      end

      def default_file_name
        return 'R2String+TxtFileName.m'
      end

      def determine_language_given_path(path)
        raise 'not going to implement'
      end

      def format_file(lang)
        filePath = Pathname.new(@options[:output_path])
        self.stringFileName = filePath.basename.to_s[0..-4]
        impl = "R2String+" + self.stringFileName + ".m"
        @options[:output_path] = filePath.dirname + impl
        result = super + "\n\n@end\n"
      end

      def format_header(lang)
        %(/**
 * Impl File
 * Generated by Twine #{Twine::VERSION}
 */

#import "R2String+#{stringFileName}.h"

static NSString *kStringsFileName = @"#{stringFileName}";

@implementation R2String \(#{stringFileName}\))
      end

      def format_section_header(section)
        "#pragma mark - #{section.name}"
      end

      def key_value_pattern
        %(\n- (NSString *)%{key}
{
    return NSLocalizedStringFromTable\(@"%{key}", kStringsFileName, @""\);
})
      end

      def format_comment(definition, lang)
        ""
      end

    end
  end
end

Twine::Formatters.formatters << Twine::Formatters::AppleObjCImpl.new
